"use client";

import React, { useCallback, useEffect, useRef } from "react";
import {
  Loader2,
  Sparkles,
} from "lucide-react";
import { motion } from "framer-motion";
import { useDashboardStore } from "@/lib/dashboard-store";
import { cleanData, analyzeData, autoGenerateDashboard, detectColumnTypes } from "@/lib/data-utils";
import type { DashboardConfig } from "@/lib/dashboard-types";

export function DashboardLoader() {
  const {
    rawData, cleanedData, columns, userInstructions,
    config, setConfig, setColumns, setFilteredData,
    isAnalyzing, setIsAnalyzing,
    addChatMessage,
  } = useDashboardStore();

  const hasTriggered = useRef(false);

  const generateDashboard = useCallback(async () => {
    if (hasTriggered.current || config) return;
    hasTriggered.current = true;
    setIsAnalyzing(true);

    try {
      // Use cleaned data if available, otherwise clean raw data
      let workingData = cleanedData.length > 0 ? cleanedData : rawData;
      let cols = columns.length > 0 ? columns : detectColumnTypes(workingData);
      if (columns.length === 0) setColumns(cols);

      // Clean data if not already cleaned
      const { data, report } = cleanData(workingData);
      workingData = data;

      const transformation = analyzeData(workingData, cols);
      const autoConfig = autoGenerateDashboard(workingData, cols, report, transformation);

      // Try AI-powered analysis
      const fetchWithRetry = async (attempt: number): Promise<Response> => {
        const res = await fetch("/api/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            data: workingData.slice(0, 500),
            columns: cols,
            userInstructions: userInstructions || undefined,
          }),
        });
        if ((res.status === 502 || res.status === 504) && attempt < 2) {
          console.log(`[analyze] Gateway timeout (${res.status}), retrying... attempt ${attempt + 1}`);
          await new Promise((r) => setTimeout(r, 2000));
          return fetchWithRetry(attempt + 1);
        }
        return res;
      };

      const res = await fetchWithRetry(0);

      if (!res.ok) {
        throw new Error(`Server returned ${res.status}`);
      }

      let result: Record<string, unknown>;
      try {
        result = await res.json();
      } catch {
        throw new Error("Invalid response from server");
      }

      if (result.kpis || result.charts) {
        const dashboardConfig: DashboardConfig = {
          ...autoConfig,
          title: result.title || autoConfig.title,
          layout: result.selected_layout || autoConfig.layout,
          kpis: (result.kpis && result.kpis.length > 0 ? result.kpis : autoConfig.kpis).map(
            (k: Record<string, unknown>, i: number) => ({
              ...k,
              id: (k.id as string) || `kpi-${i}`,
            })
          ),
          charts: (result.charts && result.charts.length > 0 ? result.charts : autoConfig.charts).map(
            (c: Record<string, unknown>, i: number) => ({
              ...c,
              id: (c.id as string) || `chart-${i}`,
            })
          ),
          filters: (result.filters && result.filters.length > 0 ? result.filters : autoConfig.filters).map(
            (f: Record<string, unknown>, i: number) => ({
              ...f,
              id: (f.id as string) || `filter-${i}`,
              selectedValues: [],
            })
          ),
          interactions: autoConfig.interactions,
          style: autoConfig.style,
        };

        setConfig(dashboardConfig);
        addChatMessage({
          id: `msg-ai-${Date.now()}`,
          role: "assistant",
          content: result.ai_message || "Dashboard generated successfully! Ask me to modify any chart or layout.",
          timestamp: Date.now(),
        });
      } else {
        // Fallback to auto-generated config
        setConfig(autoConfig);
        addChatMessage({
          id: `msg-ai-${Date.now()}`,
          role: "assistant",
          content: "Dashboard generated from your data. You can ask me to modify any chart, KPI, or layout!",
          timestamp: Date.now(),
        });
      }
    } catch (err) {
      console.error("Dashboard generation failed:", err);
      // Fallback: auto-generate
      let workingData = cleanedData.length > 0 ? cleanedData : rawData;
      const cols = columns.length > 0 ? columns : detectColumnTypes(workingData);
      const { data, report } = cleanData(workingData);
      const transformation = analyzeData(data, cols);
      const autoConfig = autoGenerateDashboard(data, cols, report, transformation);
      setConfig(autoConfig);
    } finally {
      setIsAnalyzing(false);
    }
  }, [rawData, cleanedData, columns, userInstructions, config, setConfig, setColumns, setFilteredData, setIsAnalyzing, addChatMessage]);

  useEffect(() => {
    generateDashboard();
  }, [generateDashboard]);

  return (
    <div className="w-full flex flex-col items-center justify-center py-20 gap-4">
      <motion.div
        animate={{ rotate: 360 }}
        transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
      >
        <Sparkles className="w-12 h-12 text-[#f0c040]" />
      </motion.div>
      <div className="text-center space-y-2">
        <h2 className="text-xl font-semibold">Generating Your Dashboard...</h2>
        <p className="text-sm text-muted-foreground flex items-center justify-center gap-2">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
          AI is analyzing your data and creating visualizations
        </p>
      </div>
    </div>
  );
}
